version: "2.1"

services:
  postgres1:
    image: debezium/postgres
    hostname: postgres1
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - postgres_dbdata:/var/lib/postgresql/data      
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432

  zookeeper1:
    image: debezium/zookeeper
    hostname: zookeeper1
    expose:
      - "2181"
    ports:
      - "2181:2181"
    mem_limit: 512m
    mem_reservation: 256m
    volumes:
      - zoo_data:/data
      - zoo_datalog:/datalog
      - zoo_logs:/logs
    restart: always
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS="server.1=0.0.0.0:2888:3888"

  kafka1:
      image : debezium/kafka
      hostname: kafka1
      expose:
        - "9092"
      ports:
        - "9092:9092"
        - "9093:9093"
      mem_limit: 1024m
      mem_reservation: 512m
      volumes:
        - kafka_data:/kafka
      environment:
        - KAFKA_BROKER_ID=1
        - ZOOKEEPER_CONNECT=zookeeper1:2181
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
        - KAFKA_ADVERTISED_HOST_NAME=kafka1
      depends_on:
        - zookeeper1
  
  kafkaconnect:
    image : debezium/connect
    hostname: kafkaconnect
    expose:
      - "8083"
    ports:
      - "8083:8083"
    volumes:      
      - connect_data:/usr/kafkaconnect/data      
    depends_on:
      - zookeeper1
      - kafka1
      - postgres1
    environment:
      - BOOTSTRAP_SERVERS=kafka1:9092
      - GROUP_ID=1 
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_status
    
  kafkaconnector:
    build:
      context: ./connector
    hostname: kafkaconnector
    depends_on:
      - kafkaconnect
    links:
      - kafkaconnect
    volumes:
      - connector_data:/usr/kafkaconnector/data
      
volumes:
  postgres_dbdata:
    driver: local
  zoo_data:
    driver: local
  zoo_datalog:
    driver: local
  zoo_logs:
    driver: local
  kafka_data:
    driver: local
  connect_data:
    driver: local
  connector_data:
    driver: local
 